### ISSUE TITLE
Sticky element height change issue

### ISSUE THREAD

**Issue by anetecima** [garthenweb/react-stickup#28]
I'm using this module for sticky sidebar. I have dynamic content for both sidebar and the page content. 
I have issue with StyckyPlaceholder height. if StickyElement height changes, placeholder doesn't see that and i get layout issues where the sticky element is outside StickyProvider.

**Comment by garthenweb** [comment]
Hey @anetecima!

Do you think you could create a small example app to show this issue? With a reproduceable example it would be way easier to have a look and see how we can fix it.

Feel free to use the example page in this project and extend it if it makes sense to you.

**Comment by anetecima** [comment]
@garthenweb  here is a small example i put together.
https://codesandbox.io/s/serene-clarke-nbl66?file=/src/App.js

can reproduce by adding items to sidebar

**Comment by garthenweb** [comment]
@anetecima Thank you for the example. Unfortunately, it took a bit longer to come back to you. I just released [v1.12.0](https://github.com/garthenweb/react-stickup/releases/tag/v1.12.0) which contains a fix for this. Feel free to check it out!

**Comment by anetecima** [comment]
Works great right now, thank you :)
