### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by anetecima** [garthenweb/react-stickup#29]
subscriptions and asynchronous tasks should be canceled on unmount
![Screenshot_20200903_115607](https://user-images.githubusercontent.com/7693285/92094978-bfd23080-eddd-11ea-8c6d-f80c0b9af528.png)

**Comment by garthenweb** [comment]
@anetecima Thanks for the report, this should be fixed now in [v1.12.0](https://github.com/garthenweb/react-stickup/releases/tag/v1.12.0). Feel free to check it out!

**Comment by anetecima** [comment]
@garthenweb I use your slider in a project I work with on a daily basis. I have to say, I've done large research on available sticky components and this one is the most flexible and covers a lot of nontrivial cases. 

The project I have is a SPA and I always get this when changing pages, even with the fix that was added.
![Screenshot (180)](https://user-images.githubusercontent.com/7693285/108187524-3b6b3400-7117-11eb-9ffa-98d57b3f04d3.png)


I really hope it's possible to fix this issue somehow. Thanks a lot for the work you are doing here!
